openapi: 3.0.1
info:
  title: Data management subsystem
  description: Application
  version: "1.0.0"
servers:
  - url: /api
paths:
  /search:
    get:
      parameters:
        - in: path
          name: text
          schema:
            type: string
          required: false
          description: Search string
        - in: path
          name: filters
          required: false
          description: Filtering
          schema:
            type: string
        - in: path
          name: sort
          required: false
          description: Sorting
          schema:
            type: string
        - in: path
          name: limit
          required: false
          description: Pagination
          schema:
            type: integer
            minimum: 0
            maximum: 15
        - in: path
          name: offset
          required: false
          description: Pagination
          schema:
            type: integer
            minimum: 0

      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                oneOf:
                  - $ref: '#/components/schemas/ResultResponse'
        "400":
          description: BAD REQUEST
          content:
            application/json:
              schema:
                type: object
                oneOf:
                  - $ref: '#/components/schemas/ResultResponse'
        "500":
          description: INTERNAL SERVER ERROR
          content:
            application/json:
              schema:
                type: object
                oneOf:
                  - $ref: '#/components/schemas/ResultResponse'

  /product:
    get:
      parameters:
        - in: path
          name: productId
          schema:
            type: string

      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                oneOf:
                  - $ref: '#/components/schemas/ResultResponse'
        "400":
          description: BAD REQUEST
          content:
            application/json:
              schema:
                type: object
                oneOf:
                  - $ref: '#/components/schemas/ResultResponse'
        "500":
          description: INTERNAL SERVER ERROR
          content:
            application/json:
              schema:
                type: object
                oneOf:
                  - $ref: '#/components/schemas/ResultResponse'

    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'

      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                oneOf:
                  - $ref: '#/components/schemas/ResultResponse'
        "400":
          description: BAD REQUEST
          content:
            application/json:
              schema:
                type: object
                oneOf:
                  - $ref: '#/components/schemas/ResultResponse'
        "500":
          description: INTERNAL SERVER ERROR
          content:
            application/json:
              schema:
                type: object
                oneOf:
                  - $ref: '#/components/schemas/ResultResponse'

  /feedback:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Feedback'

      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                oneOf:
                  - $ref: '#/components/schemas/ResultResponse'
        "400":
          description: BAD REQUEST
          content:
            application/json:
              schema:
                type: object
                oneOf:
                  - $ref: '#/components/schemas/ResultResponse'
        "500":
          description: INTERNAL SERVER ERROR
          content:
            application/json:
              schema:
                type: object
                oneOf:
                  - $ref: '#/components/schemas/ResultResponse'
components:
  schemas:
    ResultResponse:
      type: object
      properties:
        errorCode:
          type: integer
        errorMessage:
          type: string
        result:
          type: object
          nullable: true

    Product:
      type: object
      properties:
        id:
          type: string
        category:
          type: object
          oneOf:
            - $ref: '#/components/schemas/Category'
        vendor:
          type: object
          oneOf:
            - $ref: '#/components/schemas/Vendor'
        sourceId:
          type: string
        name:
          type: string
        description:
          type: string
        price:
          type: integer
        measurement:
          type: string
        quantity:
          type: integer
        saledQuantity:
          type: integer
        characteristics:
          type: array
          items:
            $ref: '#/components/schemas/Characteristic'
        rating:
          type: integer
        link:
          type: string
        images:
          type: array
          items:
            $ref: '#/components/schemas/Image'
        feedback:
          type: array
          items:
            $ref: '#/components/schemas/Feedback'

    ProductList:
      type: object
      properties:
        results:
          type: array
          items:
            $ref: '#/components/schemas/Product'

    SearchResultList:
      type: object
      properties:
        total:
          type: integer
        page:
          type: object
          oneOf:
            - $ref: '#/components/schemas/Pagination'
        results:
          type: array
          items:
            $ref: '#/components/schemas/ShortProduct'

    ShortProduct:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        price:
          type: integer
        quantity:
          type: integer
        image:
          type: object
          oneOf:
            - $ref: '#/components/schemas/Image'
    Category:
      type: object
      properties:
        id:
          type: string
        name:
          type: string

    Vendor:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        link:
          type: string
          nullable: true
        image:
          type: object
          nullable: true
          oneOf:
            - $ref: '#/components/schemas/Image'

    Characteristic:
      type: object
      properties:
        name:
          type: string
        value:
          type: string
        measurement:
          type: string
          nullable: true

    Image:
      type: object
      properties:
        id:
          type: string
        link:
          type: string

    Feedback:
      type: object
      properties:
        id:
          type: string
        productId:
          type: string
        fullName:
          type: string
        email:
          type: string
        description:
          type: string

    Pagination:
      type: object
      properties:
        limit:
          type: integer
          minimum: 0
          maximum: 15
        offset:
          type: integer
          minimum: 0
