openapi: 3.0.1
info:
  title: Data management subsystem
  description: Application
  version: "1.0.0"
servers:
  - url: /api
paths:
  /search:
    get:
      parameters:
        - in: query
          name: text
          schema:
            type: string
          required: false
          description: Search string
        - in: query
          name: filters
          required: false
          description: Filtering
          schema:
            type: string
        - in: query
          name: sort
          required: false
          description: Sorting
          schema:
            type: string
        - in: query
          name: limit
          required: false
          description: Pagination
          schema:
            type: integer
            minimum: 0
            maximum: 15
        - in: query
          name: offset
          required: false
          description: Pagination
          schema:
            type: integer
            minimum: 0

      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                oneOf:
                  - $ref: '../../../../openapi.yaml#/components/schemas/ResultResponse'
        "400":
          description: BAD REQUEST
          content:
            application/json:
              schema:
                type: object
                oneOf:
                  - $ref: '../../../../openapi.yaml#/components/schemas/ResultResponse'
        "500":
          description: INTERNAL SERVER ERROR
          content:
            application/json:
              schema:
                type: object
                oneOf:
                  - $ref: '../../../../openapi.yaml#/components/schemas/ResultResponse'

  /product:
    get:
      parameters:
        - in: query
          name: productId
          schema:
            type: string

      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                oneOf:
                  - $ref: '../../../../openapi.yaml#/components/schemas/ResultResponse'
        "400":
          description: BAD REQUEST
          content:
            application/json:
              schema:
                type: object
                oneOf:
                  - $ref: '../../../../openapi.yaml#/components/schemas/ResultResponse'
        "500":
          description: INTERNAL SERVER ERROR
          content:
            application/json:
              schema:
                type: object
                oneOf:
                  - $ref: '../../../../openapi.yaml#/components/schemas/ResultResponse'

  /feedback:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../../../../openapi.yaml#/components/schemas/Feedback'

      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                oneOf:
                  - $ref: '../../../../openapi.yaml#/components/schemas/ResultResponse'
        "400":
          description: BAD REQUEST
          content:
            application/json:
              schema:
                type: object
                oneOf:
                  - $ref: '../../../../openapi.yaml#/components/schemas/ResultResponse'
        "500":
          description: INTERNAL SERVER ERROR
          content:
            application/json:
              schema:
                type: object
                oneOf:
                  - $ref: '../../../../openapi.yaml#/components/schemas/ResultResponse'

