openapi: 3.0.1
info:
  title: Data management subsystem
  description: Application
  version: "1.0.0"
servers:
  - url: /api
paths:
  /product/list:
    get:
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                oneOf:
                  - $ref: '#/components/schemas/ResultResponse'
        "500":
          description: INTERNAL SERVER ERROR
          content:
            application/json:
              schema:
                type: object
                oneOf:
                  - $ref: '#/components/schemas/ResultResponse'

  /product:
    get:
      parameters:
        - in: query
          name: sourceId
          schema:
            type: string

      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                oneOf:
                  - $ref: '../../../../openapi.yaml#/components/schemas/ResultResponse'
        "400":
          description: BAD REQUEST
          content:
            application/json:
              schema:
                type: object
                oneOf:
                  - $ref: '../../../../openapi.yaml#/components/schemas/ResultResponse'
        "500":
          description: INTERNAL SERVER ERROR
          content:
            application/json:
              schema:
                type: object
                oneOf:
                  - $ref: '../../../../openapi.yaml#/components/schemas/ResultResponse'

components:
  schemas:
    ResultResponse:
      type: object
      properties:
        errorCode:
          type: integer
        errorMessage:
          type: string
        result:
          type: object
          nullable: true
          oneOf:
            - $ref: '../../../../openapi.yaml#/components/schemas/ProductList'
